trigger:
  branches:
    include:
      - master

schedules:
- cron: "0 14 * * *"         # Daily at 2:00 PM (cron uses UTC; adjust if needed)
  displayName: "Daily Build at 2 PM"
  branches:
    include:
      - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    mvn clean compile
  displayName: 'Maven Clean and Compile'

- script: |
    mvn test
  displayName: 'Run Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'

- script: |
    mvn package
  displayName: 'Maven Package'

# Send email notification with test results
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $smtpServer = "smtp.gmail.com"
      $smtpPort = 587
      $smtpFrom = "dhiral@zerotimesolutions.com"
      $smtpTo = "dhiral@zerotimesolutions.com"
      $smtpUsername = "your-email@gmail.com"
      $smtpPassword = "your-app-password"  # Use App Password, NOT your normal password!

      $subject = "Test Results for Build $buildNumber: $buildStatus"
      $body = @"
      <p>Test results for Build $buildNumber:</p>
      <p>Status: $buildStatus</p>
      <p>View details: <a href='$buildUrl'>$buildUrl</a></p>
    "@

    try {
    $smtpClient = New-Object System.Net.Mail.SmtpClient($smtpServer, $smtpPort)
    $smtpClient.EnableSsl = $true
    $smtpClient.Credentials = New-Object System.Net.NetworkCredential($smtpUsername, $smtpPassword)
    
    $mailMessage = New-Object System.Net.Mail.MailMessage
    $mailMessage.From = $smtpFrom
    $mailMessage.To.Add($smtpTo)
    $mailMessage.Subject = $subject
    $mailMessage.Body = $body
    $mailMessage.IsBodyHtml = $true

    $smtpClient.Send($mailMessage)
    Write-Host "Email sent successfully."
  }
  catch {
    Write-Error "Error sending email: $_"
}

  condition: always()
  displayName: 'Send Email Notification'   
